### ISSUE TITLE
Make v2 latest on NPM

### ISSUE THREAD

**Issue by jaydenseric** [koajs/jwt#82] opened 2017-03-01 03:55 UTC
v2 should be the latest on NPM now that Koa v2 is the latest.

**Comment by sc0ttyd** [comment] 2017-03-01 07:36
You're right - node 7.6 has finally given us native async / await. Since koa have released v2.1 under the `latest` tag, rather than `next`, we should too so that `npm install koa koa-jwt` works as intended. I'll get on the case.

**Comment by sc0ttyd** [comment] 2017-03-01 08:02
Fixed in https://github.com/koajs/jwt/pull/83

**Comment by sc0ttyd** [comment] 2017-03-01 08:10
koa-jwt 2.2.3 is now `latest` on npm :tada: 
<img width="668" alt="screen shot 2017-03-01 at 08 07 59" src="https://cloud.githubusercontent.com/assets/323439/23451078/3a0a748c-fe56-11e6-92cf-23c9ae4a11e7.png">

**Closed** 2017-03-01 08:20 UTC
