### ISSUE TITLE
Support Koa v2

### ISSUE THREAD

**Issue by b3njamin** [koajs/jwt#34] opened 2016-02-23 10:40 UTC
Update the middleware to koa2.

**Comment by oleole90** [comment] 2016-03-11 17:05
Facing the same problem. Have you( @b3njamin ) found any koa2 supported jwt middleware?

**Comment by stiang** [comment] 2016-03-11 19:22
Hi, my understanding is that koa2 won’t be released until async/await is properly supported, which could take quite a while. Is it possible for a middleware to support both versions at the same time? If not, we’d have to support koa in a different branch. Do any of you have any thoughts on this?

**Comment by oleole90** [comment] 2016-03-11 19:54
[This](https://github.com/rkusa/koa-passport/issues/46) is how basically everyone else is doing to support KOA v2.

**Comment by fl0w** [comment] 2016-03-13 15:08
So whoever needs this before a proper `koa-jwt@next` release (if author decides to follow the unofficial convention), you could simply wrap it using koa-convert.

```js
const jwt = require('koa-jwt')
const convert = require('koa-convert')

// to sign
app.use(ctx => {
  let payload = { /* ... */ }
  ctx.body = jwt.sign(payload, process.env.JWT_SECRET) // or whatever hash you use
})

// to verify
app.use(convert(jwt({ secret: process.env.JWT_SECRET })))
app.use(ctx => {
  ctx.body = ctx.state.user // tada!
})
```

**Comment by fl0w** [comment] 2016-03-13 15:12
@stiang I think it'll require two separate branches unless you want to do some runtime version check (not sure about this). As @oleole90 noted the convention is to use next that supports koa@2.

**Comment by isikfsc** [comment] 2016-04-09 16:50
As it seems after the last post in this issue thread, 27 days ago, koa.js v2 has been released for 17 days. What is the middleware to use with koa.js for using jwt?

**Comment by stiang** [comment] 2016-04-09 16:58
I’d be happy to release koa-jwt@next if someone came up with a working PR. I’m struggling to find the time to do it myself.

**Comment by fl0w** [comment] 2016-04-09 19:14
@stiang I'll do it. Give me a few, and I'll send a PR.

**Comment by isikfsc** [comment] 2016-04-20 12:59
how is it going on this update task?

**Comment by stiang** [comment] 2016-04-20 21:29
@fl0w Can you provide a status report on the PR? I completely understand if you haven’t found the time, but it would be nice to know where we’re at.

**Comment by fl0w** [comment] 2016-04-20 23:03
@stiang dang, this went right past me, I apologize. Did a first pass, broke most test so I'll need to take a look at what's up there. I'll update here or with a WIP PR when I get back from the road tomorrow.

**Comment by fl0w** [comment] 2016-04-20 23:09
As a side note; Koa@2 converts all legacy (Koa@1) middleware on use, but logs a deprecation warning. The current version should "just work" out of the box. Let me know if it doesn't.

**Comment by stiang** [comment] 2016-04-21 05:52
@fl0w Thanks for the update! @isikfsc You seem quite interested in this, so maybe you have some experience with Koa2? Would you mind testing the auto-convert mechanism that @fl0w mentions? I personally haven’t played with Koa2 at all yet.

**Comment by leo** [comment] 2016-04-21 15:21
@fl0w Are you sure that Koa v2 automatically converts legacy middleware on use? I mean, there's a [special package](https://github.com/koajs/convert) that has been created for that purpose so why should it it already be built-in? 🙈

@stiang I've tried several things, but it looks like koa-jwt isn't working without [koa-convert](https://github.com/koajs/convert) on Koa v2. [Here](https://github.com/muffinjs/server/blob/master/index.js#L23)'s an example (just remove the "convert" wrapper and it will stop working).

**Comment by fl0w** [comment] 2016-04-21 15:30
@leo I'm pretty sure, because I made that PR and had it merged at koajs/koa#683. It does exactly what you do, for you. Did you update Koa@next recently? I'll have a closer look at this in the evening (as promised)

**Comment by leo** [comment] 2016-04-21 15:35
@fl0w Hmm, that's really weird! As you can see in the `package.json`, I'm currently at `v2.0.0` of Koa (the latest one of all releases). Yeah, I've spent a few hours today upgrading the app to v2. Thank you for looking into it! 👍

**Comment by fl0w** [comment] 2016-04-21 15:35
@leo Ah, just noticed what's up. Router composes for you, and thus the deprecation in Koa is never hit.

You are correct, if you're using router today you need to convert manually.
On the contrary, if you did:
```
const Koa = require('koa')
const jwt = require('koa-jwt')
const app = new Koa()
app.use(jwt(...).unless(..)) // converts for you and displays deprecation warning.
```

**Comment by leo** [comment] 2016-04-21 15:37
@fl0w Ahhhh! 😊 I guess I'll move them to `app.use` then!

**Comment by fl0w** [comment] 2016-04-21 15:39
@leo Or just convert manually, there's nothing wrong with that. I'd argue its better for you to keep it as intended with a manual convert which you can remove (the convert) once `koa-jwt@next` hits the shelves!

**Comment by leo** [comment] 2016-04-21 15:41
@fl0w Yeah, seems like a better idea (just noticed that I need to bind JWT to a certain path). I'd also like to avoid the deprecation warnings... ^^

**Comment by fl0w** [comment] 2016-04-21 15:44
@stiang Unless you disagree, I'm going to exclude "promisification" as per [your comment](https://github.com/koajs/jwt/issues/32#issuecomment-172806526) in this sweep. Alternatively, I could just solidify my `jwt-then` package (and possibly transfer it to jonathans thenable organisation on github) and use it instead.

**Comment by stiang** [comment] 2016-04-21 16:28
@flow Yes, removing the promisification would be a good thing - please do :)

**Comment by isikfsc** [comment] 2016-04-22 16:18
@stiang actually I haven't worked with koav2 yet. I have just thought that maybe I can start my new project with koav2 rather than koav1. I have checked if middlewares I need is up to v2,  only this one seems not.

**Comment by fl0w** [comment] 2016-04-22 21:25
Soon, epic tiredness prolongs the PR.

**Comment by nfantone** [comment] 2016-04-25 13:28
Any work on this? It'd be awesome to have this published as `@next`. We've done the same thing on a number of modules (like [json-error](https://github.com/koajs/json-error).

**Comment by fl0w** [comment] 2016-04-25 13:35
I'm contemplating just creating a separate package. `koa-unless` needs updating as well (or I need to convert within `koa-jwt@next`, which isn't nice at all tbh)

**Comment by nfantone** [comment] 2016-04-25 13:56
@fl0w You mean a separate `koa-jwt-v2` package of sorts?

**Comment by fl0w** [comment] 2016-04-25 13:59
@nfantone no, `simple-koa-jwt` type thing.
I don't actually use `koa-jwt`, and for some reason life gets in my way currently.

**Comment by stiang** [comment] 2016-04-25 14:00
@nfantone I would like to get @next released too, but I’m unsure what the status currently is. 

@fl0w Sorry, I’m not quite sure I understand what you mean. Is there some technical reason why we can’t do the @next PR as planned? What is the benefit of a separate package? Or are you just unable to find the time to do the PR?

**Comment by fl0w** [comment] 2016-04-25 14:02
@stiang Sorry, I'll elaborate. I'm having issues finding the time to refactor the tests. Also `koa-unless` which `koa-jwt` is dependent on does not have a `@next` branch, and so we'll need to convert it (unless) using `koa-convert` or PR that repo as well.

**Comment by stiang** [comment] 2016-04-25 14:06
@fl0w OK, I understand now, thanks for the clarification.

I guess we’re kind of stuck for now then, unless someone else steps up. Anyone up for it?

**Comment by nfantone** [comment] 2016-04-25 14:12
(I feel like I've read the word _unless_ too many times).

@stiang I could step up! What's exactly needed then? Convert this to a Koa2 middleware, right? Anything else?

Before that, I'd like to have functionality from #39 merged. Could we do that?

**Comment by stiang** [comment] 2016-04-25 18:12
@nfantone Awesome :) Yeah, basically just make it work with v2 in a separate branch, I believe. It would also be nice if you could remove the "promisification"/forwarding of the JWT methods in the process and update the tests (if needed). 

I just merged #39.

**Comment by fl0w** [comment] 2016-04-25 18:54
> if you could remove the "promisification"/forwarding of the JWT methods in the process

You can use [jwt-then](http://github.com/fl0w/jwt-then) if you want. MIT and on [npm](https://www.npmjs.com/package/jwt-then)

**Comment by nfantone** [comment] 2016-04-26 04:50
Ok, almost all done here. The only thing that doesn't work is supporting `koa-unless`. Even after Koa2 automatic middleware conversion, its magic doesn't kick in. I'm gonna need to take another spin at it.

You can checkout current work @ https://github.com/nfantone/jwt/tree/next
 
Meanwhile, @stiang, you could create a new `next` branch or whatever to use as base for the upcoming PR.

**Comment by stiang** [comment] 2016-04-26 14:00
@nfantone Excellent work! I’ve created a remote branch called "koa-v2".

**Comment by nfantone** [comment] 2016-04-26 14:16
Here: #40 

You can track progress there. I'll go ahead and update koa-unless now.

**Comment by nfantone** [comment] 2016-05-10 15:00
@stiang Maybe close this now?

**Comment by stiang** [comment] 2016-05-10 19:27
@nfantone Indeed, closing. 

Support for Koa v2 is now available using the `koa2` tag with npm, like so:

`npm install koa-jwt@koa2`

**Closed by stiang** 2016-05-10 19:27 UTC

**Comment by cyberwombat** [comment] 2016-07-24 01:27
Might want to update the Koa [wiki](https://github.com/koajs/koa/wiki)  with mention that is supports V2.
